### ISSUE TITLE
[BUG] -AutoReply AutoReplyMessage Set

### ISSUE THREAD

**Issue by dansfilms** [FaxHax/BugTracker#1]
**Describe the bug**
When using -AutoReply AutoReplyMessage {Message} the bot only takes the first char, it is unable to be set to a string with spaces"

**To Reproduce**
1. Go into the discord bot
2. Type Command -AutoReply AutoReplyMessage (Message here with spaces between words) 
3. Success
   autoReplyMessage has been set to: I

**Expected behavior**
Be able to use set the AutoReplyMessage to a string longer than 1 char

**Screenshots**
![image](https://user-images.githubusercontent.com/65269878/159826377-85ecadc3-f63d-450d-a92b-de9c68c8b2fe.png)

**Comment by RemainingToast** [comment]
fixed in 1.4.0
