### ISSUE TITLE
[FEATURE] Have specific queueUpdateNumber Notifcations

### ISSUE THREAD

**Issue by dansfilms** [FaxHax/BugTracker#4]
**Is your feature request related to a problem? Please describe.**
Have a setting to notify you when the queue position is a specific number 

**Describe the solution you'd like**
Add a command to notifications or something similar to send a notification when queue position = 100, 50, 25, 10, etc

**Additional context**
FaxHax DMs from bot: 

Queue Position is 100!
Queue Position is 50!
Queue Position is 25!

**Comment by RemainingToast** [comment]
Added in 1.4.0
